/**
* @file
* @brief Automatically generated by the XML code generator to be used by XML parser.

* This source file is generated based on the XML schema.
* It contains C structure *xs_element_t* that holds all the schema properties of XML elelments.
* Pass this *xs_element_t* strcuture of root element *PurchaseOrder_root* as an argument to XML parser.

* For further details refer,
* https://github.com/kiishor/xml_code_generator
* https://github.com/kiishor/miniML-Parser
*/

#include <stdlib.h>
#include <stdbool.h>
#include <float.h>

#include "PurchaseOrder.h"

extern void shipToCallback(uint32_t occurrence, void* const content, void* context);

static const xs_element_t BillTo_descendant[] =
{
    [0].Name.String = "name",
    [0].Name.Length = 4,
    [0].MinOccur    = 1,
    [0].MaxOccur    = 1,
    [0].Callback    = NULL,
    [0].Target.Type    = EN_RELATIVE,
    [0].Target.Offset  = offsetof(BillTo_t, name),
    [0].Content.Type   = EN_STRING_DYNAMIC,
    [0].Content.Facet.String.MinLength = 0,
    [0].Content.Facet.String.MaxLength = 4294967295,

    [1].Name.String = "street",
    [1].Name.Length = 6,
    [1].MinOccur    = 1,
    [1].MaxOccur    = 1,
    [1].Callback    = NULL,
    [1].Target.Type    = EN_RELATIVE,
    [1].Target.Offset  = offsetof(BillTo_t, street),
    [1].Content.Type   = EN_STRING_DYNAMIC,
    [1].Content.Facet.String.MinLength = 0,
    [1].Content.Facet.String.MaxLength = 4294967295,

    [2].Name.String = "city",
    [2].Name.Length = 4,
    [2].MinOccur    = 1,
    [2].MaxOccur    = 1,
    [2].Callback    = NULL,
    [2].Target.Type    = EN_RELATIVE,
    [2].Target.Offset  = offsetof(BillTo_t, city),
    [2].Content.Type   = EN_STRING_DYNAMIC,
    [2].Content.Facet.String.MinLength = 0,
    [2].Content.Facet.String.MaxLength = 4294967295,

    [3].Name.String = "state",
    [3].Name.Length = 5,
    [3].MinOccur    = 1,
    [3].MaxOccur    = 1,
    [3].Callback    = NULL,
    [3].Target.Type    = EN_RELATIVE,
    [3].Target.Offset  = offsetof(BillTo_t, state),
    [3].Content.Type   = EN_STRING_DYNAMIC,
    [3].Content.Facet.String.MinLength = 0,
    [3].Content.Facet.String.MaxLength = 4294967295,

    [4].Name.String = "zip",
    [4].Name.Length = 3,
    [4].MinOccur    = 1,
    [4].MaxOccur    = 1,
    [4].Callback    = NULL,
    [4].Target.Type    = EN_RELATIVE,
    [4].Target.Offset  = offsetof(BillTo_t, zip),
    [4].Content.Type   = EN_INT32,
    [4].Content.Facet.Int.MinValue = -2147483648,
    [4].Content.Facet.Int.MaxValue = 2147483647,
};

static const xs_attribute_t BillTo_attribute[] =
{
    [0].Name.String = "country",
    [0].Name.Length = 7,
    [0].Target.Type    = EN_RELATIVE,
    [0].Target.Offset  = offsetof(BillTo_t, country),
    [0].Content.Type   = EN_STRING_DYNAMIC,
    [0].Content.Facet.String.MinLength = 0,
    [0].Content.Facet.String.MaxLength = 4294967295,
    [0].Use         = EN_OPTIONAL,
};

static const xs_element_t ShipTo_descendant[] =
{
    [0].Name.String = "name",
    [0].Name.Length = 4,
    [0].MinOccur    = 1,
    [0].MaxOccur    = 1,
    [0].Callback    = NULL,
    [0].Target.Type    = EN_RELATIVE,
    [0].Target.Offset  = offsetof(ShipTo_t, name),
    [0].Content.Type   = EN_STRING_DYNAMIC,
    [0].Content.Facet.String.MinLength = 0,
    [0].Content.Facet.String.MaxLength = 4294967295,

    [1].Name.String = "street",
    [1].Name.Length = 6,
    [1].MinOccur    = 1,
    [1].MaxOccur    = 1,
    [1].Callback    = NULL,
    [1].Target.Type    = EN_RELATIVE,
    [1].Target.Offset  = offsetof(ShipTo_t, street),
    [1].Content.Type   = EN_STRING_DYNAMIC,
    [1].Content.Facet.String.MinLength = 0,
    [1].Content.Facet.String.MaxLength = 4294967295,

    [2].Name.String = "city",
    [2].Name.Length = 4,
    [2].MinOccur    = 1,
    [2].MaxOccur    = 1,
    [2].Callback    = NULL,
    [2].Target.Type    = EN_RELATIVE,
    [2].Target.Offset  = offsetof(ShipTo_t, city),
    [2].Content.Type   = EN_STRING_DYNAMIC,
    [2].Content.Facet.String.MinLength = 0,
    [2].Content.Facet.String.MaxLength = 4294967295,

    [3].Name.String = "state",
    [3].Name.Length = 5,
    [3].MinOccur    = 1,
    [3].MaxOccur    = 1,
    [3].Callback    = NULL,
    [3].Target.Type    = EN_RELATIVE,
    [3].Target.Offset  = offsetof(ShipTo_t, state),
    [3].Content.Type   = EN_STRING_DYNAMIC,
    [3].Content.Facet.String.MinLength = 0,
    [3].Content.Facet.String.MaxLength = 4294967295,

    [4].Name.String = "zip",
    [4].Name.Length = 3,
    [4].MinOccur    = 1,
    [4].MaxOccur    = 1,
    [4].Callback    = NULL,
    [4].Target.Type    = EN_RELATIVE,
    [4].Target.Offset  = offsetof(ShipTo_t, zip),
    [4].Content.Type   = EN_INT32,
    [4].Content.Facet.Int.MinValue = -2147483648,
    [4].Content.Facet.Int.MaxValue = 2147483647,
};

static const xs_attribute_t ShipTo_attribute[] =
{
    [0].Name.String = "country",
    [0].Name.Length = 7,
    [0].Target.Type    = EN_RELATIVE,
    [0].Target.Offset  = offsetof(ShipTo_t, country),
    [0].Content.Type   = EN_STRING_DYNAMIC,
    [0].Content.Facet.String.MinLength = 0,
    [0].Content.Facet.String.MaxLength = 4294967295,
    [0].Use         = EN_OPTIONAL,
};

static const xs_element_t PurchaseOrder_descendant[] =
{
    [0].Name.String = "ShipTo",
    [0].Name.Length = 6,
    [0].MinOccur    = 1,
    [0].MaxOccur    = 2,
    [0].Callback    = shipToCallback,
    [0].Target.Type    = EN_RELATIVE,
    [0].Target.Offset  = offsetof(PurchaseOrder_t, ShipTo),
    [0].Target.Size    = sizeof(ShipTo_t),
    [0].Content.Type   = EN_NO_XML_DATA_TYPE,
    [0].Attribute_Quantity = 1,
    [0].Attribute          = ShipTo_attribute,
    [0].Child_Quantity = 5,
    [0].Child_Order    = EN_SEQUENCE,
    [0].Child          = ShipTo_descendant,

    [1].Name.String = "BillTo",
    [1].Name.Length = 6,
    [1].MinOccur    = 1,
    [1].MaxOccur    = 1,
    [1].Callback    = NULL,
    [1].Target.Type    = EN_RELATIVE,
    [1].Target.Offset  = offsetof(PurchaseOrder_t, BillTo),
    [1].Content.Type   = EN_NO_XML_DATA_TYPE,
    [1].Attribute_Quantity = 1,
    [1].Attribute          = BillTo_attribute,
    [1].Child_Quantity = 5,
    [1].Child_Order    = EN_SEQUENCE,
    [1].Child          = BillTo_descendant,
};

static const xs_attribute_t PurchaseOrder_attribute[] =
{
    [0].Name.String = "xmlns",
    [0].Name.Length = 5,
    [0].Use         = EN_OPTIONAL,

    [1].Name.String = "xsi:noNamespaceSchemaLocation",
    [1].Name.Length = 29,
    [1].Use         = EN_OPTIONAL,

    [2].Name.String = "OrderDate",
    [2].Name.Length = 9,
    [2].Target.Type    = EN_RELATIVE,
    [2].Target.Offset  = offsetof(PurchaseOrder_t, OrderDate),
    [2].Content.Type   = EN_DATE,
    [2].Use         = EN_OPTIONAL,
};

const xs_element_t PurchaseOrder_root =
{
    .Name.String = "PurchaseOrder",
    .Name.Length = 13,
    .MinOccur    = 1,
    .MaxOccur    = 1,
    .Callback    = NULL,
    .Target.Type    = EN_RELATIVE,
    .Target.Offset  = 0,
    .Content.Type   = EN_NO_XML_DATA_TYPE,
    .Attribute_Quantity = 3,
    .Attribute          = PurchaseOrder_attribute,
    .Child_Quantity = 2,
    .Child_Order    = EN_SEQUENCE,
    .Child          = PurchaseOrder_descendant,
};
